cloud:
  aws:
    credentials:
      accessKey: AKIAVKPG4SJHYT42KFO7
      secretKey: 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
    s3:
      bucket: challengers-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB