= Reviews API
reviews-api-docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[resources-reviews]]
== Reviews

[[resources-reviews-addReview]]
=== Review 생성

operation::reviews/addReview[snippets='http-request,request-headers,request-fields,http-response']

[[resources-reviews-deleteReview]]
=== Review 삭제

operation::reviews/deleteReview[snippets='http-request,path-parameters,request-headers,http-response']

[[resources-reviews-updateReview]]
=== Review 수정

operation::reviews/updateReview[snippets='http-request,path-parameters,request-headers,request-fields,http-response']

[[resources-reviews-showReviews]]
== 리뷰 조회

operation::reviews/showReviews[snippets='http-request,path-parameters,request-headers,request-parameters,http-response,response-fields']

---

p2p

[[resources-reviews-getReviewCount]]
== 리뷰 갯수 조회

특정 챌린지에 작성된 리뷰 갯수를 조회한다.

operation::reviews/getReviewCount[snippets='http-request,path-parameters,http-response']

[[resources-reviews-getStarRatingAvg]]
== 리뷰 평균 별점 조회

특정 챌린지의 평균 별점을 조회한다.

operation::reviews/getStarRatingAvg[snippets='http-request,path-parameters,http-response']

[[resources-reviews-deleteByChallengeId]]
== 챌린지 ID로 리뷰 삭제

특정 챌린지에 작성된 모든 리뷰들을 삭제한다.

operation::reviews/deleteReviewsByChallengeId[snippets='http-request,request-parameters,http-response']