server:
  port: 8080
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service #로그인
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/signin
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service #회원가입
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service #내정보 조회
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/user/me
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service #내정보 수정
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/user/me
            - Method=PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service #프로필 요청
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/user/global/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderAnonymousFilter
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: challenge-service # 비 로그인 사용자
          uri: lb://CHALLENGE-SERVICE
          predicates:
            - Path=/challenge-service/api/challenge/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/challenge-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderAnonymousFilter
        - id: challenge-service # 로그인 사용자
          uri: lb://CHALLENGE-SERVICE
          predicates:
            - Path=/challenge-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/challenge-service/(?<segment>.*), /$\{segment}
        - id: challenge-service # event microservice
          uri: lb://CHALLENGE-SERVICE
          predicates:
            - Path=/challenge-service/do-challenge-update-event
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/challenge-service/(?<segment>.*), /$\{segment}

        - id: review-service # 비 로그인 사용자
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/api/reviews/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/review-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderAnonymousFilter
        - id: review-service # 로그인 사용자
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/review-service/(?<segment>.*), /$\{segment}

        - id: point-service
          uri: lb://POINT-SERVICE
          predicates:
            - Path=/point-service/api/point/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/point-service/(?<segment>.*), /$\{segment}

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderAnonymousFilter
            - RewritePath=/event-service/(?<segment>.*), /$\{segment}

token:
  accessTokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
  accessTokenExpirationMsec: 3600000 #1000*60*60 1시간